# Chezmoi data file
# https://www.chezmoi.io/user-guide/manage-machine-to-machine-differences/
# Version: 2.0.0
#
# This file contains:
# - Package lists for automated installation
# - Theme colors and font configurations
# - Package feature flags (which optional configs to deploy)
#
# NOTE: User info, platform detection, and machine type are in .chezmoi.toml.tmpl
# NOTE: Use .chezmoi.local.toml for machine-specific overrides


# ============================================================================
# Theme Colors
# ============================================================================
# Referenced in: neovim, starship, wezterm, eza/vivid configs
# Override active theme in .chezmoi.local.toml: [data] theme = "onedark"
# Available themes: spaceduck, onedark, gruvbox-material, tokyonight, tokyonight-storm, dracula, kanagawa

theme:
  name: "spaceduck"  # Active theme
  
  # Spaceduck - Official palette from pineapplegiant/spaceduck
  spaceduck:
    background: "#0f111b"
    foreground: "#ecf0c1"
    purple: "#f2ce00"      # ANSI magenta in their palette
    pink: "#ce6f8f"
    green: "#5ccc96"
    orange: "#e33400"      # ANSI red
    blue: "#00a3cc"        # ANSI blue
    cyan: "#7a5ccc"        # ANSI cyan in their palette
    yellow: "#b3a1e6"      # ANSI yellow in their palette
  
  # OneDark - navarasu/onedark.nvim
  onedark:
    background: "#282c34"
    foreground: "#abb2bf"
    purple: "#c678dd"
    pink: "#e06c75"
    green: "#98c379"
    orange: "#d19965"
    blue: "#61afef"
    cyan: "#56b6c2"
    yellow: "#e5c07b"
  
  # Gruvbox Material - sainnhe/gruvbox-material
  gruvbox-material:
    background: "#1d2021"
    foreground: "#d4be98"
    purple: "#d3869b"
    pink: "#ea6962"
    green: "#a9b665"
    orange: "#e78a4e"
    blue: "#7daea3"
    cyan: "#89b482"
    yellow: "#d8a657"
  
  # Tokyo Night - folke/tokyonight.nvim (night variant)
  tokyonight:
    background: "#1a1b26"
    foreground: "#c0caf5"
    purple: "#bb9af7"
    pink: "#f7768e"
    green: "#9ece6a"
    orange: "#ff9e64"
    blue: "#7aa2f7"
    cyan: "#7dcfff"
    yellow: "#e0af68"
  
  # Tokyo Night Storm - folke/tokyonight.nvim (storm variant)
  tokyonight-storm:
    background: "#24283b"
    foreground: "#c0caf5"
    purple: "#bb9af7"
    pink: "#f7768e"
    green: "#9ece6a"
    orange: "#ff9e64"
    blue: "#7aa2f7"
    cyan: "#7dcfff"
    yellow: "#e0af68"
  
  # Dracula - Official spec from draculatheme.com/spec
  dracula:
    background: "#282a36"
    foreground: "#f8f8f2"
    purple: "#bd93f9"
    pink: "#ff79c6"
    green: "#50fa7b"
    orange: "#ffb86c"
    blue: "#8be9fd"       # cyan in official spec
    cyan: "#8be9fd"
    yellow: "#f1fa8c"
  
  # Kanagawa - rebelot/kanagawa.nvim (wave variant)
  kanagawa:
    background: "#1f1f28"  # sumiInk3
    foreground: "#dcd7ba"  # fujiWhite
    purple: "#957fb8"      # oniViolet
    pink: "#d27e99"        # sakuraPink
    green: "#98bb6c"       # springGreen
    orange: "#ffa066"      # surimiOrange
    blue: "#7e9cd8"        # crystalBlue
    cyan: "#7fb4ca"        # springBlue
    yellow: "#e6c384"      # carpYellow

# ============================================================================
# Theme Mappings
# ============================================================================
# Maps chezmoi theme names to application-specific theme identifiers

theme_mappings:
  # Neovim colorscheme plugin/command names
  neovim:
    spaceduck: "spaceduck"                   # pineapplegiant/spaceduck
    onedark: "onedark"                       # navarasu/onedark.nvim
    gruvbox-material: "gruvbox-material"     # sainnhe/gruvbox-material
    tokyonight: "tokyonight"                 # folke/tokyonight.nvim
    tokyonight-storm: "tokyonight-storm"     # folke/tokyonight.nvim
    dracula: "dracula"                       # dracula/vim
    kanagawa: "kanagawa"                     # rebelot/kanagawa.nvim
  
  # WezTerm builtin colorscheme names
  wezterm:
    spaceduck: "Spaceduck (Gogh)"
    onedark: "OneDark (base16)"
    gruvbox-material: "Gruvbox Material (Gogh)"
    tokyonight: "Tokyo Night"
    tokyonight-storm: "Tokyo Night Storm"
    dracula: "Dracula (Official)"
    kanagawa: "Kanagawa (Gogh)"
  
  # Starship palette names (defined in starship.toml)
  starship:
    spaceduck: "spaceduck"
    onedark: "onedark_pro4"
    gruvbox-material: "gruvbox_dark_material"
    tokyonight: "tokyonight"
    tokyonight-storm: "tokyonight_storm"
    dracula: "dracula"
    kanagawa: "kanagawa"
  
  # Vivid theme names (for LS_COLORS generation)
  vivid:
    spaceduck: "spaceduck"
    onedark: "onedark"
    gruvbox-material: "gruvbox-dark"
    tokyonight: "tokyonight"
    tokyonight-storm: "tokyonight-storm"
    dracula: "dracula"
    kanagawa: "molokai"  # fallback - vivid doesn't have kanagawa
  
  # Bat (cat with syntax highlighting) and Delta (git diff)
  # Use custom .tmTheme files generated from our color palettes
  bat:
    spaceduck: "spaceduck"
    onedark: "onedark"
    gruvbox-material: "gruvbox-material"
    tokyonight: "tokyonight"
    tokyonight-storm: "tokyonight-storm"
    dracula: "dracula"
    kanagawa: "kanagawa"
  
  # Delta uses same theme names as bat
  delta:
    spaceduck: "spaceduck"
    onedark: "onedark"
    gruvbox-material: "gruvbox-material"
    tokyonight: "tokyonight"
    tokyonight-storm: "tokyonight-storm"
    dracula: "dracula"
    kanagawa: "kanagawa"

# ============================================================================
# Fonts
# ============================================================================
# Referenced in: wezterm, alacritty, Windows Terminal configs
# Override in .chezmoi.local.toml: [data] font = "JetBrainsMono"

fonts:
  primary: "Hack"
  fallback: "FiraCode"
  nerd_fonts:
    - "Hack Nerd Font"
    - "FiraCode Nerd Font"
    - "JetBrainsMono Nerd Font"
    - "CascadiaCode Nerd Font"
  emoji: "Noto Color Emoji"
  symbols: "Symbols Nerd Font Mono"
  
  # Fira Code ligature settings (OpenType features)
  fira_code_stylistic_sets:
    - ss02  # >= <= != == === !== 
    - ss03  # ->
    - ss04  # >=
    - ss05  # @
    - ss08  # == === != !==
  fira_code_character_variants:
    - cv15  # &
    - cv24  # >=
    - cv29  # {}

# ============================================================================
# SSH and Authentication
# ============================================================================
# 1Password SSH agent configuration
# See SECRETS.md for setup instructions

ssh:
  agent: "1password"  # Use 1Password SSH agent
  windows_pipe: "\\\\.\\pipe\\openssh-ssh-agent"
  unix_socket: "~/.1password/agent.sock"

# ============================================================================
# Package Feature Flags
# ============================================================================
# Controls which configuration files are deployed by chezmoi
#
# Usage in templates:
#   {{- if index .package_features "rust" }}
#   # Deploy ~/.config/rust/* configs
#   {{- end }}
#
# Group flags (convenience shortcuts):
#   {{- if .package_features.essentials }}
#   # Enables: git, ssh, 1password, mise, direnv
#   {{- end }}
#
# Override in .chezmoi.local.toml:
#   [data.package_features]
#   rust = false
#   golang = false

package_features:
  # ============================================================================
  # Group Flags (convenience shortcuts)
  # ============================================================================
  essentials: true      # git, ssh, 1password, mise, direnv
  shell_tools: true     # starship, zsh, bat, eza, ripgrep, fd, fzf, zoxide, delta, vivid, wget, glow, thefuck
  languages: true       # All language runtimes (node, python, ruby, go, rust, lua)
  editors: true         # nvim, vscode
  terminals: true       # wezterm, warp, windows_terminal
  
  # ============================================================================
  # Version Control & Authentication (sane defaults)
  # ============================================================================
  git: true
  ssh: true
  1password: true
  
  # ============================================================================
  # Package & Tool Version Management (sane defaults)
  # ============================================================================
  mise: true            # Version manager (replaces asdf/nvm)
  direnv: true          # Per-directory environments
  homebrew: true        # Package manager (Linux/macOS)
  
  # ============================================================================
  # Terminal Emulators (recommended)
  # ============================================================================
  wezterm: true
  warp: true
  windows_terminal: true
  
  # ============================================================================
  # Text Editors (recommended)
  # ============================================================================
  nvim: true
  vim: true
  vscode: true
  
  # ============================================================================
  # Shell Tools (recommended)
  # ============================================================================
  starship: true        # Cross-platform prompt
  zsh: true             # Unix shells only
  powershell: true      # Windows shell
  bat: true             # Better cat
  eza: true             # Better ls
  ripgrep: true         # Fast grep
  fd: true              # Fast find
  fzf: true             # Fuzzy finder
  zoxide: true          # Smart cd
  delta: true           # Git diff viewer
  vivid: true           # LS_COLORS generator
  wget: true            # Downloader
  glow: true            # Markdown renderer
  thefuck: true         # Command correction
  btop: true            # System monitor
  
  # ============================================================================
  # Language Runtimes (optional - enable as needed)
  # ============================================================================
  rust: true
  golang: true
  python: true
  ruby: true
  lua: true
  node: true
  perl: true
  php: false
  
  # ============================================================================
  # Development Tools (optional)
  # ============================================================================
  sqlite3: true
  arduino: false
  vagrant: false        # Virtualization
  
  # ============================================================================
  # Legacy/Deprecated (disabled)
  # ============================================================================
  asdf: false           # DEPRECATED: Replaced by mise
  nvm: false            # DEPRECATED: Replaced by mise
  tinted_theming: false # DEPRECATED: Replaced by unified theme system

# ============================================================================
# Package Mapping
# ============================================================================
# Maps feature flags to actual packages per platform/manager
# This allows feature flags to control BOTH config deployment AND package installation
#
# Package manager priority on Unix:
#   1. mise - If available via mise, use it
#   2. brew - Only for tools not in mise (zsh, thefuck) and GUI apps
#   3. System pkg manager - Only build-essential
#
# Bootstrap order on Unix:
#   1. Build from source (if needed): git, curl → ~/.local/share/
#   2. Install homebrew → ~/.local/share/homebrew (Linux) or /opt/homebrew (macOS)
#   3. brew installs base tools
#   4. mise installs CLI tools and language runtimes

package_mapping:
  # Version Control & Authentication
  git:
    scoop: [git, gh, lazygit]
    winget: [Git.Git]
    brew: [git, gh, lazygit]
    mise: []
  
  ssh:
    scoop: []
    winget: []
    brew: []
    mise: []
  
  1password:
    scoop: [1password-cli]
    winget: [AgileBits.1Password]
    brew: [1password-cli]
    brew_cask: [1password]  # macOS GUI
    mise: []
  
  # Package & Tool Version Management
  mise:
    scoop: [mise]
    winget: []
    brew: [mise]
    mise: []
  
  direnv:
    scoop: []
    winget: []
    brew: []
    mise: [direnv]
  
  homebrew:
    scoop: []
    winget: []
    brew: []
    mise: []
  
  # Terminal Emulators
  wezterm:
    scoop: []
    winget: [wez.wezterm]
    brew: []
    brew_cask: [wezterm]
    mise: []
  
  warp:
    scoop: []
    winget: [Warp.Warp]
    brew: []
    brew_cask: [warp]
    mise: []
  
  windows_terminal:
    scoop: []
    winget: [Microsoft.WindowsTerminal]
    brew: []
    mise: []
  
  # Text Editors
  nvim:
    scoop: [neovim]
    winget: []
    brew: []
    mise: [neovim]
  
  vim:
    scoop: [vim]
    winget: []
    brew: [vim]
    mise: [vim]
  
  vscode:
    scoop: []
    winget: [Microsoft.VisualStudioCode]
    brew: []
    brew_cask: [visual-studio-code]
    mise: []
  
  # Shell Tools
  starship:
    scoop: [starship]
    winget: []
    brew: []
    mise: [cargo:starship]
  
  zsh:
    scoop: []
    winget: []
    brew: [zsh]
    mise: []
  
  powershell:
    scoop: []
    winget: [Microsoft.PowerShell]
    brew: []
    brew_cask: [powershell]
    mise: []
  
  bat:
    scoop: [bat]
    winget: []
    brew: []
    mise: [cargo:bat]
  
  eza:
    scoop: [eza]
    winget: []
    brew: []
    mise: [cargo:eza]
  
  ripgrep:
    scoop: [ripgrep]
    winget: []
    brew: []
    mise: [cargo:ripgrep]
  
  fd:
    scoop: [fd]
    winget: []
    brew: []
    mise: [cargo:fd-find]
  
  fzf:
    scoop: [fzf]
    winget: []
    brew: []
    mise: [fzf]
  
  zoxide:
    scoop: [zoxide]
    winget: []
    brew: []
    mise: [cargo:zoxide]
  
  delta:
    scoop: [delta]
    winget: []
    brew: []
    mise: [cargo:git-delta]
  
  vivid:
    scoop: [vivid]
    winget: []
    brew: []
    mise: [cargo:vivid]
  
  wget:
    scoop: [wget, curl]
    winget: []
    brew: [wget, curl]
    mise: []
  
  glow:
    scoop: [glow]
    winget: []
    brew: []
    mise: [glow]
  
  thefuck:
    scoop: []
    winget: []
    brew: [thefuck]
    mise: []
  
  btop:
    scoop: [btop]
    winget: []
    brew: [btop]
    mise: [btop]
  
  # Language Runtimes (all via mise)
  rust:
    scoop: []
    winget: []
    brew: []
    mise_runtime:
      name: rust
      version: stable
  
  golang:
    scoop: []
    winget: []
    brew: []
    mise_runtime:
      name: go
      version: latest
  
  python:
    scoop: []
    winget: []
    brew: []
    mise_runtime:
      name: python
      version: "3.12"
  
  ruby:
    scoop: []
    winget: []
    brew: []
    mise_runtime:
      name: ruby
      version: latest
  
  lua:
    scoop: []
    winget: []
    brew: []
    mise_runtime:
      name: lua
      version: latest
  
  node:
    scoop: []
    winget: []
    brew: []
    mise_runtime:
      name: node
      version: lts
  
  perl:
    scoop: []
    winget: []
    brew: []
    mise_runtime:
      name: perl
      version: latest
  
  php:
    scoop: []
    winget: []
    brew: []
    mise_runtime:
      name: php
      version: latest
  
  # Development Tools
  sqlite3:
    scoop: [sqlite]
    winget: []
    brew: [sqlite]
    mise: []
  
  arduino:
    scoop: []
    winget: []
    brew: []
    brew_cask: [arduino-ide]
    mise: []
  
  vagrant:
    scoop: []
    winget: []
    brew: []
    brew_cask: [vagrant]
    mise: []

# Always-installed packages (not controlled by feature flags)
always_install:
  scoop:
    - chezmoi
    - jq
    - yq
    - make
    - 7zip
  
  winget:
    - 7zip.7zip
  
  brew:
    - jq
    - yq
  
  mise:
    - usage
  
  mise_runtimes:
    bun: latest
    deno: latest

# Remote machine package sets
# When is_remote=true and remote_minimal=true, only install essential tools
remote_packages:
  # Minimal set for remote servers (no sudo required)
  minimal:
    runtimes:
      - node     # JavaScript runtime
      - python   # Python runtime
      - go       # Go runtime
    tools:
      - direnv   # Per-directory environment
      - fzf      # Fuzzy finder
      - ripgrep  # Fast grep
      - fd       # Fast find
      - bat      # Cat with syntax highlighting
      - delta    # Git diff viewer
      - neovim   # Text editor
  
  # Full set for remote workstations (with sudo)
  full:
    runtimes:
      - node
      - python
      - ruby
      - go
      - rust
    tools:
      - direnv
      - fzf
      - ripgrep
      - fd
      - bat
      - eza
      - delta
      - starship
      - zoxide
      - neovim
      - sqlite

# vim: ts=2 sts=2 sw=2 et
