[dock]
icon_size = 54
spacing = 16
padding = [
    0,
    24,
]
negative_vertical_offset = 8
background_color = "#1a1928"
background_opacity = 1.0
indicator_color = "#f38ba8"
auto_hide = true
auto_hide_delay_ms = 150
auto_show_delay_ms = 600
corner_radius = 12
magnification = 1.7000000476837158
locked = false
hide_windows_taskbar = true
hide_in_fullscreen = true

[[items]]
name = "Start Menu"
icon = 'E:\Themes\Sweet Paranoia Icon Theme by niivu MARCH 29 2022\candy-icons\bcompare.ico'
special = "start_menu"

[[items]]
name = "Recycle Bin"
icon = 'E:\Themes\Sweet Paranoia Icon Theme by niivu MARCH 29 2022\candy-icons\etcher.ico'
special = "recycle_bin"

[[items]]
name = "This PC"
icon = 'E:\Themes\Sweet Paranoia Icon Theme by niivu MARCH 29 2022\candy-icons\folder2-.ico'
special = "this_pc"

[[items]]
name = "User Folder"
icon = 'E:\Themes\Sweet Paranoia Icon Theme by niivu MARCH 29 2022\candy-icons\folder2-me.ico'
special = "user_folder"

[[items]]
name = "---"
separator = true

[[items]]
name = "Brave"
path = 'C:\Users\Randall\AppData\Local\BraveSoftware\Brave-Browser\Application\brave.exe'
icon = 'E:\Themes\Sweet Paranoia Icon Theme by niivu MARCH 29 2022\candy-icons\brave.ico'

[[items]]
name = "Firefox"
path = 'C:\Program Files\Firefox Developer Edition\firefox.exe'
icon = 'E:\Themes\Sweet Paranoia Icon Theme by niivu MARCH 29 2022\candy-icons\firefox-nightly.ico'

[[items]]
name = "Chrome"
path = 'C:\Program Files\Google\Chrome\Application\chrome.exe'
icon = 'E:\Themes\Sweet Paranoia Icon Theme by niivu MARCH 29 2022\PNGS\Apps\google-chrome.png'
args = ["--disable-windows10-custom-titlebar"]

[[items]]
name = "Edge"
path = 'C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe'
icon = 'E:\Themes\Sweet Paranoia Icon Theme by niivu MARCH 29 2022\candy-icons\microsoft-edge.ico'

[[items]]
name = "---"
separator = true

[[items]]
name = "VS Code"
path = 'C:\Users\Randall\AppData\Local\Programs\Microsoft VS Code\Code.exe'
icon = 'E:\Themes\Sweet Paranoia Icon Theme by niivu MARCH 29 2022\candy-icons\code.ico'

[[items]]
name = "Warp"
path = 'C:\Users\Randall\AppData\Local\Programs\Warp\warp.exe'
icon = 'E:\Themes\Sweet Paranoia Icon Theme by niivu MARCH 29 2022\candy-icons\terminix.ico'

[[items]]
name = "WezTerm"
path = 'C:\Program Files\WezTerm\wezterm-gui.exe'
icon = 'E:\Themes\Sweet Paranoia Icon Theme by niivu MARCH 29 2022\candy-icons\terminal.ico'

[[items]]
name = "Windows Terminal"
path = 'C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.23.12811.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe'
icon = 'E:\Themes\Sweet Paranoia Icon Theme by niivu MARCH 29 2022\candy-icons\terminator.ico'

[[items]]
name = "---"
separator = true

[[items]]
name = "Steam"
path = 'C:\Users\Randall\scoop\apps\steam\current\steam.exe'
icon = 'E:\Themes\Sweet Paranoia Icon Theme by niivu MARCH 29 2022\candy-icons\steam.ico'

[[items]]
name = "Vortex"
path = 'C:\Program Files\Black Tree Gaming Ltd\Vortex\Vortex.exe'
icon = 'E:\Themes\Sweet Paranoia Icon Theme by niivu MARCH 29 2022\candy-icons\atom.ico'

[[items]]
name = "Lossless Scaling"
path = 'A:\SteamGames\steamapps\common\Lossless Scaling\LosslessScaling.exe'
icon = 'E:\Themes\Sweet Paranoia Icon Theme by niivu MARCH 29 2022\candy-icons\freealchemist.ico'

[[items]]
name = "RTSS"
path = 'C:\Program Files (x86)\RivaTuner Statistics Server\RTSS.exe'
icon = 'E:\Themes\Sweet Paranoia Icon Theme by niivu MARCH 29 2022\PNGS\settings.png'

[[items]]
name = "Xbox"
path = 'C:\Program Files\WindowsApps\Microsoft.GamingApp_2512.1001.34.0_x64__8wekyb3d8bbwe\XboxPcTray.exe'
icon = 'E:\Themes\Sweet Paranoia Icon Theme by niivu MARCH 29 2022\candy-icons\clamav.ico'

[[items]]
name = "---"
separator = true

[[items]]
name = "Slack"
path = 'C:\Users\Randall\AppData\Local\slack\slack.exe'
icon = 'E:\Themes\Sweet Paranoia Icon Theme by niivu MARCH 29 2022\candy-icons\slack.ico'

[[items]]
name = "Spotify"
path = 'C:\Users\Randall\AppData\Roaming\Spotify\Spotify.exe'
icon = 'E:\Themes\Sweet Paranoia Icon Theme by niivu MARCH 29 2022\candy-icons\spotify-client.ico'

[[items]]
name = "---"
separator = true

[[items]]
name = "Action Center"
icon = 'E:\Themes\Sweet Paranoia Icon Theme by niivu MARCH 29 2022\candy-icons\preferences-desktop-notification-bell.ico'
special = "action_center"

[[items]]
name = "Settings"
icon = 'E:\Themes\Sweet Paranoia Icon Theme by niivu MARCH 29 2022\candy-icons\preferences-system.ico'
special = "settings"

[[items]]
name = "System Tray (Hidden Icons)"
icon = 'E:\Themes\Sweet Paranoia Icon Theme by niivu MARCH 29 2022\candy-icons\preferences-desktop-icons.ico'
special = "system_tray"

[[items]]
name = "Quick Settings"
icon = 'E:\Themes\Sweet Paranoia Icon Theme by niivu MARCH 29 2022\candy-icons\preferences-system-windows.ico'
special = "quick_settings"
