[colors]
ansi = [
  "#1d2021", #bg
  "#fb4934", #red
  "#b8bb26", #green
  "#fabd2f", #yellow
  "#83a598", #blue
  "#d3869b", #purple
  "#8ec07c", #aqua
  "#ebdbb2"  #fg0
]
brights = [
  "#1d2021",
  "#fb4934",
  "#b8bb26",
  "#fabd2f",
  "#83a598",
  "#d3869b",
  "#8ec07c",
  "#ebdbb2"
]

background = '#1d2021'
foreground = '#ebdbb2'
cursor_bg = '#ebdbb2'
cursor_fg = '#1d2021'
cursor_border = '#ebdbb2'
selection_bg = '#ebdbb2'
selection_fg = '#3c3836' #bg3/4

[colors.indexed]

[metadata]
author = 'Me'
name = 'GruvboxDarkHardOrig'

