[colors]
ansi = [
  "#1d2021", #bg
  "#ea6962", #red
  "#a9b665", #green
  "#d8a657", #yellow
  "#7daea3", #blue
  "#d3869b", #purple
  "#89b482", #aqua
  "#d4be98"  #fg0
]
brights = [
  "#1d2021",
  "#ea6962",
  "#a9b665",
  "#d8a657",
  "#7daea3",
  "#d3869b",
  "#89b482",
  "#d4be98"
]

background = '#1d2021'
foreground = '#d4be98'
cursor_bg = '#d4be98'
cursor_fg = '#1d2021'
cursor_border = '#d4be98'
selection_bg = '#d4be98'
selection_fg = '#3c3836' #bg3/4

[colors.indexed]

[metadata]
author = 'Me'
name = 'GruvboxDarkHardMaterial'
