[colors]
ansi = [
  "#282828", #bg
  "#f2594b", #red
  "#b0b846", #green
  "#e9b143", #yellow
  "#80aa9e", #blue
  "#d3869b", #purple
  "#8bba7f", #aqua
  "#e2cca9"  #fg0
]
brights = [
  "#282828", #bg
  "#f2594b", #red
  "#b0b846", #green
  "#e9b143", #yellow
  "#80aa9e", #blue
  "#d3869b", #purple
  "#8bba7f", #aqua
  "#e2cca9"  #fg0
]

background = '#282828'
foreground = '#e2cca9'
cursor_bg = '#e2cca9'
cursor_fg = '#282828'
cursor_border = '#e2cca9'
selection_bg = '#e2cca9'
selection_fg = '#3c3836' #bg3/4

[colors.indexed]

[metadata]
author = 'Me'
name = 'GruvboxDarkMediumMix'
