shell = "zsh -c '{}'"
default-scheme = "base16-gruvbox-material-dark-medium"

[[items]]
path = "https://github.com/tinted-theming/tinted-shell"
name = "tinted-shell"
hook = ". %f"
themes-dir = "scripts"

[[items]]
path = "https://github.com/tinted-theming/base16-vim"
name = "base16-vim"
themes-dir = "colors"

# [[items]]
# path = "https://github.com/tinted-theming/base16-fzf"
# name = "fzf"
# themes-dir = "bash"
# hook = ". %f"
